version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    expose:
      - 40001
    ports:
      - 40001:80
    networks:
      - internal
    volumes:
      - ./app/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./app/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log

  mariadb:
    image: mariadb
    expose:
      - 3307
    ports:
      - 3307:3306
    networks:
      - internal
    volumes:
      - mariadb:/var/lib/mysql
      - ./mysql/medicaldb.sql:/docker-entrypoint-initdb.d/medicaldb.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_TCP_PORT: 3307
      MYSQL_UNIX_PORT: 3307

  pma:
    image: phpmyadmin
    expose:
      - 40002
    ports:
      - 40002:80
    networks:
      - internal
    environment:
      # Disable arbitrary server connection; use the configured host and port
      - PMA_ARBITRARY=0
      # Set the host for phpMyAdmin to connect to
      - PMA_HOST=mariadb
      # Set the port for phpMyAdmin to connect to
      - PMA_PORT=3307

# Define the "internal" network for communication between containers
networks:
  internal:

# Define a local volume driver for mariadb data
volumes:
  mariadb:
    driver: local

